### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by dirsors** [Arawn-Davies/pcsx2oom#1]
This error is show while compiling:

/usr/local/ps2dev/ee/lib/gcc/mips64r5900el-ps2-elf/11.3.0/../../../../mips64r5900el-ps2-elf/bin/ld: m_menu.o:(.bss+0x278): multiple definition of `currentWadName'; g_game.o:(.bss+0xcb8): first defined here
collect2: erro: ld returned 1 exit status
make: *** [/usr/local/ps2dev/ps2sdk/samples/Makefile.eeglobal:82: ps2doom.elf] Erro 1

**Comment by Arawn-Davies** [comment]
Just fixed, going to close :)
